# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:

  #PostgreSQL Database for the application
  db-postgres:
    image: "postgres:9.6-alpine"
    container_name: db-postgres
    #Volume mounted for database for the storage
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=DB_BK
      - POSTGRES_USER=youssfi
      - POSTGRES_PASSWORD=1234

  #Back-end Spring Boot Application
  bank-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: .
    container_name: bank-app

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=db-postgres
      - POSTGRES_DB=DB_BK
      - POSTGRES_USER=youssfi
      - POSTGRES_PASSWORD=1234
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - db-postgres
  #Fron-end Angular Application
  angular-ui:
    build: ./angular-ui
    container_name: angular-ui
    ports:
      - 4200:80
    links:
      - bank-app
#Volumes for DB data
volumes:
  db-data: